/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gateway_stats.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gateway_stats.pb-c.h"
void   system_stats__init
                     (SystemStats         *message)
{
  static const SystemStats init_value = SYSTEM_STATS__INIT;
  *message = init_value;
}
size_t system_stats__get_packed_size
                     (const SystemStats *message)
{
  assert(message->base.descriptor == &system_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t system_stats__pack
                     (const SystemStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &system_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t system_stats__pack_to_buffer
                     (const SystemStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &system_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SystemStats *
       system_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SystemStats *)
     protobuf_c_message_unpack (&system_stats__descriptor,
                                allocator, len, data);
}
void   system_stats__free_unpacked
                     (SystemStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &system_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wan_stats__init
                     (WanStats         *message)
{
  static const WanStats init_value = WAN_STATS__INIT;
  *message = init_value;
}
size_t wan_stats__get_packed_size
                     (const WanStats *message)
{
  assert(message->base.descriptor == &wan_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wan_stats__pack
                     (const WanStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wan_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wan_stats__pack_to_buffer
                     (const WanStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wan_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WanStats *
       wan_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WanStats *)
     protobuf_c_message_unpack (&wan_stats__descriptor,
                                allocator, len, data);
}
void   wan_stats__free_unpacked
                     (WanStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wan_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lan_stats__init
                     (LanStats         *message)
{
  static const LanStats init_value = LAN_STATS__INIT;
  *message = init_value;
}
size_t lan_stats__get_packed_size
                     (const LanStats *message)
{
  assert(message->base.descriptor == &lan_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lan_stats__pack
                     (const LanStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lan_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lan_stats__pack_to_buffer
                     (const LanStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lan_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LanStats *
       lan_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LanStats *)
     protobuf_c_message_unpack (&lan_stats__descriptor,
                                allocator, len, data);
}
void   lan_stats__free_unpacked
                     (LanStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lan_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipv6_monitoring_stats__init
                     (IPv6MonitoringStats         *message)
{
  static const IPv6MonitoringStats init_value = IPV6_MONITORING_STATS__INIT;
  *message = init_value;
}
size_t ipv6_monitoring_stats__get_packed_size
                     (const IPv6MonitoringStats *message)
{
  assert(message->base.descriptor == &ipv6_monitoring_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipv6_monitoring_stats__pack
                     (const IPv6MonitoringStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipv6_monitoring_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipv6_monitoring_stats__pack_to_buffer
                     (const IPv6MonitoringStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipv6_monitoring_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IPv6MonitoringStats *
       ipv6_monitoring_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IPv6MonitoringStats *)
     protobuf_c_message_unpack (&ipv6_monitoring_stats__descriptor,
                                allocator, len, data);
}
void   ipv6_monitoring_stats__free_unpacked
                     (IPv6MonitoringStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ipv6_monitoring_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcp_stats__init
                     (TcpStats         *message)
{
  static const TcpStats init_value = TCP_STATS__INIT;
  *message = init_value;
}
size_t tcp_stats__get_packed_size
                     (const TcpStats *message)
{
  assert(message->base.descriptor == &tcp_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcp_stats__pack
                     (const TcpStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcp_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcp_stats__pack_to_buffer
                     (const TcpStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcp_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TcpStats *
       tcp_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TcpStats *)
     protobuf_c_message_unpack (&tcp_stats__descriptor,
                                allocator, len, data);
}
void   tcp_stats__free_unpacked
                     (TcpStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tcp_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   restart_count_stats__init
                     (RestartCountStats         *message)
{
  static const RestartCountStats init_value = RESTART_COUNT_STATS__INIT;
  *message = init_value;
}
size_t restart_count_stats__get_packed_size
                     (const RestartCountStats *message)
{
  assert(message->base.descriptor == &restart_count_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t restart_count_stats__pack
                     (const RestartCountStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &restart_count_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t restart_count_stats__pack_to_buffer
                     (const RestartCountStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &restart_count_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RestartCountStats *
       restart_count_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RestartCountStats *)
     protobuf_c_message_unpack (&restart_count_stats__descriptor,
                                allocator, len, data);
}
void   restart_count_stats__free_unpacked
                     (RestartCountStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &restart_count_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_details__init
                     (ClientDetails         *message)
{
  static const ClientDetails init_value = CLIENT_DETAILS__INIT;
  *message = init_value;
}
size_t client_details__get_packed_size
                     (const ClientDetails *message)
{
  assert(message->base.descriptor == &client_details__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_details__pack
                     (const ClientDetails *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_details__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_details__pack_to_buffer
                     (const ClientDetails *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_details__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientDetails *
       client_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientDetails *)
     protobuf_c_message_unpack (&client_details__descriptor,
                                allocator, len, data);
}
void   client_details__free_unpacked
                     (ClientDetails *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_details__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_stats__init
                     (ClientStats         *message)
{
  static const ClientStats init_value = CLIENT_STATS__INIT;
  *message = init_value;
}
size_t client_stats__get_packed_size
                     (const ClientStats *message)
{
  assert(message->base.descriptor == &client_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_stats__pack
                     (const ClientStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_stats__pack_to_buffer
                     (const ClientStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientStats *
       client_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientStats *)
     protobuf_c_message_unpack (&client_stats__descriptor,
                                allocator, len, data);
}
void   client_stats__free_unpacked
                     (ClientStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pid_details__init
                     (PidDetails         *message)
{
  static const PidDetails init_value = PID_DETAILS__INIT;
  *message = init_value;
}
size_t pid_details__get_packed_size
                     (const PidDetails *message)
{
  assert(message->base.descriptor == &pid_details__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pid_details__pack
                     (const PidDetails *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pid_details__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pid_details__pack_to_buffer
                     (const PidDetails *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pid_details__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PidDetails *
       pid_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PidDetails *)
     protobuf_c_message_unpack (&pid_details__descriptor,
                                allocator, len, data);
}
void   pid_details__free_unpacked
                     (PidDetails *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pid_details__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pid_stats__init
                     (PidStats         *message)
{
  static const PidStats init_value = PID_STATS__INIT;
  *message = init_value;
}
size_t pid_stats__get_packed_size
                     (const PidStats *message)
{
  assert(message->base.descriptor == &pid_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pid_stats__pack
                     (const PidStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pid_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pid_stats__pack_to_buffer
                     (const PidStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pid_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PidStats *
       pid_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PidStats *)
     protobuf_c_message_unpack (&pid_stats__descriptor,
                                allocator, len, data);
}
void   pid_stats__free_unpacked
                     (PidStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pid_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   report__init
                     (Report         *message)
{
  static const Report init_value = REPORT__INIT;
  *message = init_value;
}
size_t report__get_packed_size
                     (const Report *message)
{
  assert(message->base.descriptor == &report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t report__pack
                     (const Report *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t report__pack_to_buffer
                     (const Report *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Report *
       report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Report *)
     protobuf_c_message_unpack (&report__descriptor,
                                allocator, len, data);
}
void   report__free_unpacked
                     (Report *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor system_stats__field_descriptors[18] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(SystemStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SystemStats, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SystemStats, firmware),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmac",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SystemStats, cmac),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SystemStats, uptime),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_usage",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SystemStats, cpu_usage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "free_memory",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SystemStats, free_memory),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slab_memory",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SystemStats, slab_memory),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avail_memory",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SystemStats, avail_memory),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cached_mem",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SystemStats, cached_mem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slab_unreclaim",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SystemStats, slab_unreclaim),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadavg_1min",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SystemStats, loadavg_1min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadavg_5min",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SystemStats, loadavg_5min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadavg_15min",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SystemStats, loadavg_15min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rootfs_used_kb",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SystemStats, rootfs_used_kb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rootfs_total_kb",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SystemStats, rootfs_total_kb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tmpfs_used_kb",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SystemStats, tmpfs_used_kb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tmpfs_total_kb",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SystemStats, tmpfs_total_kb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned system_stats__field_indices_by_name[] = {
  8,   /* field[8] = avail_memory */
  9,   /* field[9] = cached_mem */
  3,   /* field[3] = cmac */
  5,   /* field[5] = cpu_usage */
  2,   /* field[2] = firmware */
  6,   /* field[6] = free_memory */
  13,   /* field[13] = loadavg_15min */
  11,   /* field[11] = loadavg_1min */
  12,   /* field[12] = loadavg_5min */
  1,   /* field[1] = model */
  15,   /* field[15] = rootfs_total_kb */
  14,   /* field[14] = rootfs_used_kb */
  7,   /* field[7] = slab_memory */
  10,   /* field[10] = slab_unreclaim */
  0,   /* field[0] = timestamp_ms */
  17,   /* field[17] = tmpfs_total_kb */
  16,   /* field[16] = tmpfs_used_kb */
  4,   /* field[4] = uptime */
};
static const ProtobufCIntRange system_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 18 }
};
const ProtobufCMessageDescriptor system_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SystemStats",
  "SystemStats",
  "SystemStats",
  "",
  sizeof(SystemStats),
  18,
  system_stats__field_descriptors,
  system_stats__field_indices_by_name,
  1,  system_stats__number_ranges,
  (ProtobufCMessageInit) system_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wan_stats__field_descriptors[15] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(WanStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface_status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WanStats, interface_status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WanStats, ipv4_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_address",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WanStats, ipv6_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway_status",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WanStats, gateway_status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_loss",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(WanStats, packet_loss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latency",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(WanStats, latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jitter",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(WanStats, jitter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dns_time",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(WanStats, dns_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_bytes",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WanStats, rx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_bytes",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WanStats, tx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_dropped",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WanStats, rx_dropped),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_dropped",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WanStats, tx_dropped),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_lease",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WanStats, ipv4_lease),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_lease",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WanStats, ipv6_lease),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wan_stats__field_indices_by_name[] = {
  8,   /* field[8] = dns_time */
  4,   /* field[4] = gateway_status */
  1,   /* field[1] = interface_status */
  2,   /* field[2] = ipv4_address */
  13,   /* field[13] = ipv4_lease */
  3,   /* field[3] = ipv6_address */
  14,   /* field[14] = ipv6_lease */
  7,   /* field[7] = jitter */
  6,   /* field[6] = latency */
  5,   /* field[5] = packet_loss */
  9,   /* field[9] = rx_bytes */
  11,   /* field[11] = rx_dropped */
  0,   /* field[0] = timestamp_ms */
  10,   /* field[10] = tx_bytes */
  12,   /* field[12] = tx_dropped */
};
static const ProtobufCIntRange wan_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor wan_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WanStats",
  "WanStats",
  "WanStats",
  "",
  sizeof(WanStats),
  15,
  wan_stats__field_descriptors,
  wan_stats__field_indices_by_name,
  1,  wan_stats__number_ranges,
  (ProtobufCMessageInit) wan_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lan_stats__field_descriptors[7] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(LanStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LanStats, ipv4_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LanStats, ipv6_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_bytes",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LanStats, rx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_bytes",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LanStats, tx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_dropped",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LanStats, rx_dropped),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_dropped",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LanStats, tx_dropped),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lan_stats__field_indices_by_name[] = {
  1,   /* field[1] = ipv4_address */
  2,   /* field[2] = ipv6_address */
  3,   /* field[3] = rx_bytes */
  5,   /* field[5] = rx_dropped */
  0,   /* field[0] = timestamp_ms */
  4,   /* field[4] = tx_bytes */
  6,   /* field[6] = tx_dropped */
};
static const ProtobufCIntRange lan_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor lan_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LanStats",
  "LanStats",
  "LanStats",
  "",
  sizeof(LanStats),
  7,
  lan_stats__field_descriptors,
  lan_stats__field_indices_by_name,
  1,  lan_stats__number_ranges,
  (ProtobufCMessageInit) lan_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ipv6_monitoring_stats__field_descriptors[8] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(IPv6MonitoringStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "global_ipv6_address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IPv6MonitoringStats, global_ipv6_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link_local_ipv6_address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IPv6MonitoringStats, link_local_ipv6_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_reachability",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IPv6MonitoringStats, ipv6_reachability),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_latency",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(IPv6MonitoringStats, ipv4_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_latency",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(IPv6MonitoringStats, ipv6_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_packet_loss",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(IPv6MonitoringStats, ipv4_packet_loss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_packet_loss",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(IPv6MonitoringStats, ipv6_packet_loss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipv6_monitoring_stats__field_indices_by_name[] = {
  1,   /* field[1] = global_ipv6_address */
  4,   /* field[4] = ipv4_latency */
  6,   /* field[6] = ipv4_packet_loss */
  5,   /* field[5] = ipv6_latency */
  7,   /* field[7] = ipv6_packet_loss */
  3,   /* field[3] = ipv6_reachability */
  2,   /* field[2] = link_local_ipv6_address */
  0,   /* field[0] = timestamp_ms */
};
static const ProtobufCIntRange ipv6_monitoring_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ipv6_monitoring_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IPv6MonitoringStats",
  "IPv6MonitoringStats",
  "IPv6MonitoringStats",
  "",
  sizeof(IPv6MonitoringStats),
  8,
  ipv6_monitoring_stats__field_descriptors,
  ipv6_monitoring_stats__field_indices_by_name,
  1,  ipv6_monitoring_stats__number_ranges,
  (ProtobufCMessageInit) ipv6_monitoring_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tcp_stats__field_descriptors[8] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TcpStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPLostRetransmit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TcpStats, tcplostretransmit),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPRetransFail",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TcpStats, tcpretransfail),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPSackFailures",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TcpStats, tcpsackfailures),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPTimeouts",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TcpStats, tcptimeouts),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPAbortOnTimeout",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TcpStats, tcpabortontimeout),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ListenOverflows",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TcpStats, listenoverflows),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPOrigDataSent",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TcpStats, tcporigdatasent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcp_stats__field_indices_by_name[] = {
  6,   /* field[6] = ListenOverflows */
  5,   /* field[5] = TCPAbortOnTimeout */
  1,   /* field[1] = TCPLostRetransmit */
  7,   /* field[7] = TCPOrigDataSent */
  2,   /* field[2] = TCPRetransFail */
  3,   /* field[3] = TCPSackFailures */
  4,   /* field[4] = TCPTimeouts */
  0,   /* field[0] = timestamp_ms */
};
static const ProtobufCIntRange tcp_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor tcp_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TcpStats",
  "TcpStats",
  "TcpStats",
  "",
  sizeof(TcpStats),
  8,
  tcp_stats__field_descriptors,
  tcp_stats__field_indices_by_name,
  1,  tcp_stats__number_ranges,
  (ProtobufCMessageInit) tcp_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor restart_count_stats__field_descriptors[4] =
{
  {
    "fw_restart_count",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RestartCountStats, fw_restart_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_restart_time",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(RestartCountStats, n_fw_restart_time),
    offsetof(RestartCountStats, fw_restart_time),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wan_restart_count",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RestartCountStats, wan_restart_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wan_restart_time",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(RestartCountStats, n_wan_restart_time),
    offsetof(RestartCountStats, wan_restart_time),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned restart_count_stats__field_indices_by_name[] = {
  0,   /* field[0] = fw_restart_count */
  1,   /* field[1] = fw_restart_time */
  2,   /* field[2] = wan_restart_count */
  3,   /* field[3] = wan_restart_time */
};
static const ProtobufCIntRange restart_count_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor restart_count_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RestartCountStats",
  "RestartCountStats",
  "RestartCountStats",
  "",
  sizeof(RestartCountStats),
  4,
  restart_count_stats__field_descriptors,
  restart_count_stats__field_indices_by_name,
  1,  restart_count_stats__number_ranges,
  (ProtobufCMessageInit) restart_count_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_details__field_descriptors[19] =
{
  {
    "mac_address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, mac_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ip_addr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, host_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_bytes",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, tx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_bytes",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, rx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp_est_counts",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, tcp_est_counts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_synack_min_latency",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv4_synack_min_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_synack_max_latency",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv4_synack_max_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_synack_avg_latency",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv4_synack_avg_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_ack_min_latency",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv4_ack_min_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_ack_max_latency",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv4_ack_max_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_ack_avg_latency",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv4_ack_avg_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_synack_min_latency",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv6_synack_min_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_synack_max_latency",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv6_synack_max_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_synack_avg_latency",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv6_synack_avg_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_ack_min_latency",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv6_ack_min_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_ack_max_latency",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv6_ack_max_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_ack_avg_latency",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientDetails, ipv6_ack_avg_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_details__field_indices_by_name[] = {
  2,   /* field[2] = host_name */
  1,   /* field[1] = ip_addr */
  12,   /* field[12] = ipv4_ack_avg_latency */
  11,   /* field[11] = ipv4_ack_max_latency */
  10,   /* field[10] = ipv4_ack_min_latency */
  9,   /* field[9] = ipv4_synack_avg_latency */
  8,   /* field[8] = ipv4_synack_max_latency */
  7,   /* field[7] = ipv4_synack_min_latency */
  18,   /* field[18] = ipv6_ack_avg_latency */
  17,   /* field[17] = ipv6_ack_max_latency */
  16,   /* field[16] = ipv6_ack_min_latency */
  15,   /* field[15] = ipv6_synack_avg_latency */
  14,   /* field[14] = ipv6_synack_max_latency */
  13,   /* field[13] = ipv6_synack_min_latency */
  0,   /* field[0] = mac_address */
  5,   /* field[5] = rx_bytes */
  3,   /* field[3] = status */
  6,   /* field[6] = tcp_est_counts */
  4,   /* field[4] = tx_bytes */
};
static const ProtobufCIntRange client_details__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor client_details__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientDetails",
  "ClientDetails",
  "ClientDetails",
  "",
  sizeof(ClientDetails),
  19,
  client_details__field_descriptors,
  client_details__field_indices_by_name,
  1,  client_details__number_ranges,
  (ProtobufCMessageInit) client_details__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_stats__field_descriptors[3] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ClientStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ClientStats, client_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_details",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ClientStats, n_client_details),
    offsetof(ClientStats, client_details),
    &client_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_stats__field_indices_by_name[] = {
  1,   /* field[1] = client_count */
  2,   /* field[2] = client_details */
  0,   /* field[0] = timestamp_ms */
};
static const ProtobufCIntRange client_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor client_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientStats",
  "ClientStats",
  "ClientStats",
  "",
  sizeof(ClientStats),
  3,
  client_stats__field_descriptors,
  client_stats__field_indices_by_name,
  1,  client_stats__number_ranges,
  (ProtobufCMessageInit) client_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pid_details__field_descriptors[6] =
{
  {
    "pid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PidDetails, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pName",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PidDetails, pname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rss",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PidDetails, rss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pss",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PidDetails, pss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_util",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PidDetails, mem_util),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_util",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PidDetails, cpu_util),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pid_details__field_indices_by_name[] = {
  5,   /* field[5] = cpu_util */
  4,   /* field[4] = mem_util */
  1,   /* field[1] = pName */
  0,   /* field[0] = pid */
  3,   /* field[3] = pss */
  2,   /* field[2] = rss */
};
static const ProtobufCIntRange pid_details__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor pid_details__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PidDetails",
  "PidDetails",
  "PidDetails",
  "",
  sizeof(PidDetails),
  6,
  pid_details__field_descriptors,
  pid_details__field_indices_by_name,
  1,  pid_details__number_ranges,
  (ProtobufCMessageInit) pid_details__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pid_stats__field_descriptors[3] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PidStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PidStats, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid_details",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PidStats, n_pid_details),
    offsetof(PidStats, pid_details),
    &pid_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pid_stats__field_indices_by_name[] = {
  1,   /* field[1] = count */
  2,   /* field[2] = pid_details */
  0,   /* field[0] = timestamp_ms */
};
static const ProtobufCIntRange pid_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pid_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PidStats",
  "PidStats",
  "PidStats",
  "",
  sizeof(PidStats),
  3,
  pid_stats__field_descriptors,
  pid_stats__field_indices_by_name,
  1,  pid_stats__number_ranges,
  (ProtobufCMessageInit) pid_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor report__field_descriptors[9] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Report, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "systemStats",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Report, n_systemstats),
    offsetof(Report, systemstats),
    &system_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wanStats",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Report, n_wanstats),
    offsetof(Report, wanstats),
    &wan_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lanStats",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Report, n_lanstats),
    offsetof(Report, lanstats),
    &lan_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6MonStats",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Report, n_ipv6monstats),
    offsetof(Report, ipv6monstats),
    &ipv6_monitoring_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcpStats",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Report, n_tcpstats),
    offsetof(Report, tcpstats),
    &tcp_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clientStats",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Report, n_clientstats),
    offsetof(Report, clientstats),
    &client_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pidStats",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Report, n_pidstats),
    offsetof(Report, pidstats),
    &pid_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "restartCountStats",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Report, restartcountstats),
    &restart_count_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned report__field_indices_by_name[] = {
  6,   /* field[6] = clientStats */
  4,   /* field[4] = ipv6MonStats */
  3,   /* field[3] = lanStats */
  7,   /* field[7] = pidStats */
  8,   /* field[8] = restartCountStats */
  1,   /* field[1] = systemStats */
  5,   /* field[5] = tcpStats */
  0,   /* field[0] = timestamp_ms */
  2,   /* field[2] = wanStats */
};
static const ProtobufCIntRange report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Report",
  "Report",
  "Report",
  "",
  sizeof(Report),
  9,
  report__field_descriptors,
  report__field_indices_by_name,
  1,  report__number_ranges,
  (ProtobufCMessageInit) report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
