/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gateway_stats.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gateway_stats.pb-c.h"
void   gwstats__system_stats__init
                     (Gwstats__SystemStats         *message)
{
  static const Gwstats__SystemStats init_value = GWSTATS__SYSTEM_STATS__INIT;
  *message = init_value;
}
size_t gwstats__system_stats__get_packed_size
                     (const Gwstats__SystemStats *message)
{
  assert(message->base.descriptor == &gwstats__system_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__system_stats__pack
                     (const Gwstats__SystemStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__system_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__system_stats__pack_to_buffer
                     (const Gwstats__SystemStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__system_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__SystemStats *
       gwstats__system_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__SystemStats *)
     protobuf_c_message_unpack (&gwstats__system_stats__descriptor,
                                allocator, len, data);
}
void   gwstats__system_stats__free_unpacked
                     (Gwstats__SystemStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__system_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gwstats__wan_stats__init
                     (Gwstats__WanStats         *message)
{
  static const Gwstats__WanStats init_value = GWSTATS__WAN_STATS__INIT;
  *message = init_value;
}
size_t gwstats__wan_stats__get_packed_size
                     (const Gwstats__WanStats *message)
{
  assert(message->base.descriptor == &gwstats__wan_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__wan_stats__pack
                     (const Gwstats__WanStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__wan_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__wan_stats__pack_to_buffer
                     (const Gwstats__WanStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__wan_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__WanStats *
       gwstats__wan_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__WanStats *)
     protobuf_c_message_unpack (&gwstats__wan_stats__descriptor,
                                allocator, len, data);
}
void   gwstats__wan_stats__free_unpacked
                     (Gwstats__WanStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__wan_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gwstats__lan_stats__init
                     (Gwstats__LanStats         *message)
{
  static const Gwstats__LanStats init_value = GWSTATS__LAN_STATS__INIT;
  *message = init_value;
}
size_t gwstats__lan_stats__get_packed_size
                     (const Gwstats__LanStats *message)
{
  assert(message->base.descriptor == &gwstats__lan_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__lan_stats__pack
                     (const Gwstats__LanStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__lan_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__lan_stats__pack_to_buffer
                     (const Gwstats__LanStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__lan_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__LanStats *
       gwstats__lan_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__LanStats *)
     protobuf_c_message_unpack (&gwstats__lan_stats__descriptor,
                                allocator, len, data);
}
void   gwstats__lan_stats__free_unpacked
                     (Gwstats__LanStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__lan_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gwstats__ipv6_monitoring_stats__init
                     (Gwstats__IPv6MonitoringStats         *message)
{
  static const Gwstats__IPv6MonitoringStats init_value = GWSTATS__IPV6_MONITORING_STATS__INIT;
  *message = init_value;
}
size_t gwstats__ipv6_monitoring_stats__get_packed_size
                     (const Gwstats__IPv6MonitoringStats *message)
{
  assert(message->base.descriptor == &gwstats__ipv6_monitoring_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__ipv6_monitoring_stats__pack
                     (const Gwstats__IPv6MonitoringStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__ipv6_monitoring_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__ipv6_monitoring_stats__pack_to_buffer
                     (const Gwstats__IPv6MonitoringStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__ipv6_monitoring_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__IPv6MonitoringStats *
       gwstats__ipv6_monitoring_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__IPv6MonitoringStats *)
     protobuf_c_message_unpack (&gwstats__ipv6_monitoring_stats__descriptor,
                                allocator, len, data);
}
void   gwstats__ipv6_monitoring_stats__free_unpacked
                     (Gwstats__IPv6MonitoringStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__ipv6_monitoring_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gwstats__tcp_stats__init
                     (Gwstats__TcpStats         *message)
{
  static const Gwstats__TcpStats init_value = GWSTATS__TCP_STATS__INIT;
  *message = init_value;
}
size_t gwstats__tcp_stats__get_packed_size
                     (const Gwstats__TcpStats *message)
{
  assert(message->base.descriptor == &gwstats__tcp_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__tcp_stats__pack
                     (const Gwstats__TcpStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__tcp_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__tcp_stats__pack_to_buffer
                     (const Gwstats__TcpStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__tcp_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__TcpStats *
       gwstats__tcp_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__TcpStats *)
     protobuf_c_message_unpack (&gwstats__tcp_stats__descriptor,
                                allocator, len, data);
}
void   gwstats__tcp_stats__free_unpacked
                     (Gwstats__TcpStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__tcp_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gwstats__restart_count_stats__init
                     (Gwstats__RestartCountStats         *message)
{
  static const Gwstats__RestartCountStats init_value = GWSTATS__RESTART_COUNT_STATS__INIT;
  *message = init_value;
}
size_t gwstats__restart_count_stats__get_packed_size
                     (const Gwstats__RestartCountStats *message)
{
  assert(message->base.descriptor == &gwstats__restart_count_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__restart_count_stats__pack
                     (const Gwstats__RestartCountStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__restart_count_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__restart_count_stats__pack_to_buffer
                     (const Gwstats__RestartCountStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__restart_count_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__RestartCountStats *
       gwstats__restart_count_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__RestartCountStats *)
     protobuf_c_message_unpack (&gwstats__restart_count_stats__descriptor,
                                allocator, len, data);
}
void   gwstats__restart_count_stats__free_unpacked
                     (Gwstats__RestartCountStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__restart_count_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gwstats__client_details__init
                     (Gwstats__ClientDetails         *message)
{
  static const Gwstats__ClientDetails init_value = GWSTATS__CLIENT_DETAILS__INIT;
  *message = init_value;
}
size_t gwstats__client_details__get_packed_size
                     (const Gwstats__ClientDetails *message)
{
  assert(message->base.descriptor == &gwstats__client_details__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__client_details__pack
                     (const Gwstats__ClientDetails *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__client_details__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__client_details__pack_to_buffer
                     (const Gwstats__ClientDetails *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__client_details__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__ClientDetails *
       gwstats__client_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__ClientDetails *)
     protobuf_c_message_unpack (&gwstats__client_details__descriptor,
                                allocator, len, data);
}
void   gwstats__client_details__free_unpacked
                     (Gwstats__ClientDetails *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__client_details__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gwstats__client_stats__init
                     (Gwstats__ClientStats         *message)
{
  static const Gwstats__ClientStats init_value = GWSTATS__CLIENT_STATS__INIT;
  *message = init_value;
}
size_t gwstats__client_stats__get_packed_size
                     (const Gwstats__ClientStats *message)
{
  assert(message->base.descriptor == &gwstats__client_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__client_stats__pack
                     (const Gwstats__ClientStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__client_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__client_stats__pack_to_buffer
                     (const Gwstats__ClientStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__client_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__ClientStats *
       gwstats__client_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__ClientStats *)
     protobuf_c_message_unpack (&gwstats__client_stats__descriptor,
                                allocator, len, data);
}
void   gwstats__client_stats__free_unpacked
                     (Gwstats__ClientStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__client_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gwstats__pid_details__init
                     (Gwstats__PidDetails         *message)
{
  static const Gwstats__PidDetails init_value = GWSTATS__PID_DETAILS__INIT;
  *message = init_value;
}
size_t gwstats__pid_details__get_packed_size
                     (const Gwstats__PidDetails *message)
{
  assert(message->base.descriptor == &gwstats__pid_details__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__pid_details__pack
                     (const Gwstats__PidDetails *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__pid_details__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__pid_details__pack_to_buffer
                     (const Gwstats__PidDetails *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__pid_details__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__PidDetails *
       gwstats__pid_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__PidDetails *)
     protobuf_c_message_unpack (&gwstats__pid_details__descriptor,
                                allocator, len, data);
}
void   gwstats__pid_details__free_unpacked
                     (Gwstats__PidDetails *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__pid_details__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gwstats__pid_stats__init
                     (Gwstats__PidStats         *message)
{
  static const Gwstats__PidStats init_value = GWSTATS__PID_STATS__INIT;
  *message = init_value;
}
size_t gwstats__pid_stats__get_packed_size
                     (const Gwstats__PidStats *message)
{
  assert(message->base.descriptor == &gwstats__pid_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__pid_stats__pack
                     (const Gwstats__PidStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__pid_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__pid_stats__pack_to_buffer
                     (const Gwstats__PidStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__pid_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__PidStats *
       gwstats__pid_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__PidStats *)
     protobuf_c_message_unpack (&gwstats__pid_stats__descriptor,
                                allocator, len, data);
}
void   gwstats__pid_stats__free_unpacked
                     (Gwstats__PidStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__pid_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gwstats__gateway_stats__init
                     (Gwstats__GatewayStats         *message)
{
  static const Gwstats__GatewayStats init_value = GWSTATS__GATEWAY_STATS__INIT;
  *message = init_value;
}
size_t gwstats__gateway_stats__get_packed_size
                     (const Gwstats__GatewayStats *message)
{
  assert(message->base.descriptor == &gwstats__gateway_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gwstats__gateway_stats__pack
                     (const Gwstats__GatewayStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gwstats__gateway_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gwstats__gateway_stats__pack_to_buffer
                     (const Gwstats__GatewayStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gwstats__gateway_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gwstats__GatewayStats *
       gwstats__gateway_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gwstats__GatewayStats *)
     protobuf_c_message_unpack (&gwstats__gateway_stats__descriptor,
                                allocator, len, data);
}
void   gwstats__gateway_stats__free_unpacked
                     (Gwstats__GatewayStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gwstats__gateway_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gwstats__system_stats__field_descriptors[18] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, firmware),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmac",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, cmac),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, uptime),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_usage",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, cpu_usage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "free_memory",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, free_memory),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slab_memory",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, slab_memory),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avail_memory",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, avail_memory),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cached_mem",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, cached_mem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slab_unreclaim",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, slab_unreclaim),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadavg_1min",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, loadavg_1min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadavg_5min",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, loadavg_5min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadavg_15min",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, loadavg_15min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rootfs_used_kb",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, rootfs_used_kb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rootfs_total_kb",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, rootfs_total_kb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tmpfs_used_kb",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, tmpfs_used_kb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tmpfs_total_kb",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__SystemStats, tmpfs_total_kb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__system_stats__field_indices_by_name[] = {
  8,   /* field[8] = avail_memory */
  9,   /* field[9] = cached_mem */
  3,   /* field[3] = cmac */
  5,   /* field[5] = cpu_usage */
  2,   /* field[2] = firmware */
  6,   /* field[6] = free_memory */
  13,   /* field[13] = loadavg_15min */
  11,   /* field[11] = loadavg_1min */
  12,   /* field[12] = loadavg_5min */
  1,   /* field[1] = model */
  15,   /* field[15] = rootfs_total_kb */
  14,   /* field[14] = rootfs_used_kb */
  7,   /* field[7] = slab_memory */
  10,   /* field[10] = slab_unreclaim */
  0,   /* field[0] = timestamp_ms */
  17,   /* field[17] = tmpfs_total_kb */
  16,   /* field[16] = tmpfs_used_kb */
  4,   /* field[4] = uptime */
};
static const ProtobufCIntRange gwstats__system_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 18 }
};
const ProtobufCMessageDescriptor gwstats__system_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.SystemStats",
  "SystemStats",
  "Gwstats__SystemStats",
  "gwstats",
  sizeof(Gwstats__SystemStats),
  18,
  gwstats__system_stats__field_descriptors,
  gwstats__system_stats__field_indices_by_name,
  1,  gwstats__system_stats__number_ranges,
  (ProtobufCMessageInit) gwstats__system_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gwstats__wan_stats__field_descriptors[15] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface_status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, interface_status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, ipv4_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_address",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, ipv6_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway_status",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, gateway_status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_loss",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, packet_loss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latency",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jitter",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, jitter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dns_time",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, dns_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_bytes",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, rx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_bytes",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, tx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_dropped",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, rx_dropped),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_dropped",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, tx_dropped),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_lease",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, ipv4_lease),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_lease",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__WanStats, ipv6_lease),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__wan_stats__field_indices_by_name[] = {
  8,   /* field[8] = dns_time */
  4,   /* field[4] = gateway_status */
  1,   /* field[1] = interface_status */
  2,   /* field[2] = ipv4_address */
  13,   /* field[13] = ipv4_lease */
  3,   /* field[3] = ipv6_address */
  14,   /* field[14] = ipv6_lease */
  7,   /* field[7] = jitter */
  6,   /* field[6] = latency */
  5,   /* field[5] = packet_loss */
  9,   /* field[9] = rx_bytes */
  11,   /* field[11] = rx_dropped */
  0,   /* field[0] = timestamp_ms */
  10,   /* field[10] = tx_bytes */
  12,   /* field[12] = tx_dropped */
};
static const ProtobufCIntRange gwstats__wan_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor gwstats__wan_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.WanStats",
  "WanStats",
  "Gwstats__WanStats",
  "gwstats",
  sizeof(Gwstats__WanStats),
  15,
  gwstats__wan_stats__field_descriptors,
  gwstats__wan_stats__field_indices_by_name,
  1,  gwstats__wan_stats__number_ranges,
  (ProtobufCMessageInit) gwstats__wan_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gwstats__lan_stats__field_descriptors[7] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gwstats__LanStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__LanStats, ipv4_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__LanStats, ipv6_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_bytes",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__LanStats, rx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_bytes",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__LanStats, tx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_dropped",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__LanStats, rx_dropped),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_dropped",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__LanStats, tx_dropped),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__lan_stats__field_indices_by_name[] = {
  1,   /* field[1] = ipv4_address */
  2,   /* field[2] = ipv6_address */
  3,   /* field[3] = rx_bytes */
  5,   /* field[5] = rx_dropped */
  0,   /* field[0] = timestamp_ms */
  4,   /* field[4] = tx_bytes */
  6,   /* field[6] = tx_dropped */
};
static const ProtobufCIntRange gwstats__lan_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor gwstats__lan_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.LanStats",
  "LanStats",
  "Gwstats__LanStats",
  "gwstats",
  sizeof(Gwstats__LanStats),
  7,
  gwstats__lan_stats__field_descriptors,
  gwstats__lan_stats__field_indices_by_name,
  1,  gwstats__lan_stats__number_ranges,
  (ProtobufCMessageInit) gwstats__lan_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gwstats__ipv6_monitoring_stats__field_descriptors[8] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gwstats__IPv6MonitoringStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "global_ipv6_address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__IPv6MonitoringStats, global_ipv6_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link_local_ipv6_address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__IPv6MonitoringStats, link_local_ipv6_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_reachability",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__IPv6MonitoringStats, ipv6_reachability),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_latency",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__IPv6MonitoringStats, ipv4_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_latency",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__IPv6MonitoringStats, ipv6_latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_packet_loss",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__IPv6MonitoringStats, ipv4_packet_loss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_packet_loss",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__IPv6MonitoringStats, ipv6_packet_loss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__ipv6_monitoring_stats__field_indices_by_name[] = {
  1,   /* field[1] = global_ipv6_address */
  4,   /* field[4] = ipv4_latency */
  6,   /* field[6] = ipv4_packet_loss */
  5,   /* field[5] = ipv6_latency */
  7,   /* field[7] = ipv6_packet_loss */
  3,   /* field[3] = ipv6_reachability */
  2,   /* field[2] = link_local_ipv6_address */
  0,   /* field[0] = timestamp_ms */
};
static const ProtobufCIntRange gwstats__ipv6_monitoring_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor gwstats__ipv6_monitoring_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.IPv6MonitoringStats",
  "IPv6MonitoringStats",
  "Gwstats__IPv6MonitoringStats",
  "gwstats",
  sizeof(Gwstats__IPv6MonitoringStats),
  8,
  gwstats__ipv6_monitoring_stats__field_descriptors,
  gwstats__ipv6_monitoring_stats__field_indices_by_name,
  1,  gwstats__ipv6_monitoring_stats__number_ranges,
  (ProtobufCMessageInit) gwstats__ipv6_monitoring_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gwstats__tcp_stats__field_descriptors[8] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gwstats__TcpStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPLostRetransmit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__TcpStats, tcplostretransmit),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPRetransFail",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__TcpStats, tcpretransfail),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPSackFailures",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__TcpStats, tcpsackfailures),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPTimeouts",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__TcpStats, tcptimeouts),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPAbortOnTimeout",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__TcpStats, tcpabortontimeout),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ListenOverflows",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__TcpStats, listenoverflows),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TCPOrigDataSent",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__TcpStats, tcporigdatasent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__tcp_stats__field_indices_by_name[] = {
  6,   /* field[6] = ListenOverflows */
  5,   /* field[5] = TCPAbortOnTimeout */
  1,   /* field[1] = TCPLostRetransmit */
  7,   /* field[7] = TCPOrigDataSent */
  2,   /* field[2] = TCPRetransFail */
  3,   /* field[3] = TCPSackFailures */
  4,   /* field[4] = TCPTimeouts */
  0,   /* field[0] = timestamp_ms */
};
static const ProtobufCIntRange gwstats__tcp_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor gwstats__tcp_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.TcpStats",
  "TcpStats",
  "Gwstats__TcpStats",
  "gwstats",
  sizeof(Gwstats__TcpStats),
  8,
  gwstats__tcp_stats__field_descriptors,
  gwstats__tcp_stats__field_indices_by_name,
  1,  gwstats__tcp_stats__number_ranges,
  (ProtobufCMessageInit) gwstats__tcp_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gwstats__restart_count_stats__field_descriptors[4] =
{
  {
    "fw_restart_count",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__RestartCountStats, fw_restart_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_restart_time",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Gwstats__RestartCountStats, n_fw_restart_time),
    offsetof(Gwstats__RestartCountStats, fw_restart_time),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wan_restart_count",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__RestartCountStats, wan_restart_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wan_restart_time",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Gwstats__RestartCountStats, n_wan_restart_time),
    offsetof(Gwstats__RestartCountStats, wan_restart_time),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__restart_count_stats__field_indices_by_name[] = {
  0,   /* field[0] = fw_restart_count */
  1,   /* field[1] = fw_restart_time */
  2,   /* field[2] = wan_restart_count */
  3,   /* field[3] = wan_restart_time */
};
static const ProtobufCIntRange gwstats__restart_count_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gwstats__restart_count_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.RestartCountStats",
  "RestartCountStats",
  "Gwstats__RestartCountStats",
  "gwstats",
  sizeof(Gwstats__RestartCountStats),
  4,
  gwstats__restart_count_stats__field_descriptors,
  gwstats__restart_count_stats__field_indices_by_name,
  1,  gwstats__restart_count_stats__number_ranges,
  (ProtobufCMessageInit) gwstats__restart_count_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gwstats__client_details__field_descriptors[7] =
{
  {
    "mac_address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__ClientDetails, mac_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__ClientDetails, ip_addr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__ClientDetails, host_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__ClientDetails, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_bytes",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__ClientDetails, tx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_bytes",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__ClientDetails, rx_bytes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp_est_counts",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__ClientDetails, tcp_est_counts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__client_details__field_indices_by_name[] = {
  2,   /* field[2] = host_name */
  1,   /* field[1] = ip_addr */
  0,   /* field[0] = mac_address */
  5,   /* field[5] = rx_bytes */
  3,   /* field[3] = status */
  6,   /* field[6] = tcp_est_counts */
  4,   /* field[4] = tx_bytes */
};
static const ProtobufCIntRange gwstats__client_details__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor gwstats__client_details__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.ClientDetails",
  "ClientDetails",
  "Gwstats__ClientDetails",
  "gwstats",
  sizeof(Gwstats__ClientDetails),
  7,
  gwstats__client_details__field_descriptors,
  gwstats__client_details__field_indices_by_name,
  1,  gwstats__client_details__number_ranges,
  (ProtobufCMessageInit) gwstats__client_details__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gwstats__client_stats__field_descriptors[3] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gwstats__ClientStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__ClientStats, client_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_details",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gwstats__ClientStats, n_client_details),
    offsetof(Gwstats__ClientStats, client_details),
    &gwstats__client_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__client_stats__field_indices_by_name[] = {
  1,   /* field[1] = client_count */
  2,   /* field[2] = client_details */
  0,   /* field[0] = timestamp_ms */
};
static const ProtobufCIntRange gwstats__client_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gwstats__client_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.ClientStats",
  "ClientStats",
  "Gwstats__ClientStats",
  "gwstats",
  sizeof(Gwstats__ClientStats),
  3,
  gwstats__client_stats__field_descriptors,
  gwstats__client_stats__field_indices_by_name,
  1,  gwstats__client_stats__number_ranges,
  (ProtobufCMessageInit) gwstats__client_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gwstats__pid_details__field_descriptors[6] =
{
  {
    "pid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__PidDetails, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pName",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gwstats__PidDetails, pname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rss",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__PidDetails, rss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pss",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__PidDetails, pss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_util",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__PidDetails, mem_util),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_util",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__PidDetails, cpu_util),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__pid_details__field_indices_by_name[] = {
  5,   /* field[5] = cpu_util */
  4,   /* field[4] = mem_util */
  1,   /* field[1] = pName */
  0,   /* field[0] = pid */
  3,   /* field[3] = pss */
  2,   /* field[2] = rss */
};
static const ProtobufCIntRange gwstats__pid_details__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor gwstats__pid_details__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.PidDetails",
  "PidDetails",
  "Gwstats__PidDetails",
  "gwstats",
  sizeof(Gwstats__PidDetails),
  6,
  gwstats__pid_details__field_descriptors,
  gwstats__pid_details__field_indices_by_name,
  1,  gwstats__pid_details__number_ranges,
  (ProtobufCMessageInit) gwstats__pid_details__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gwstats__pid_stats__field_descriptors[3] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gwstats__PidStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gwstats__PidStats, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid_details",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gwstats__PidStats, n_pid_details),
    offsetof(Gwstats__PidStats, pid_details),
    &gwstats__pid_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__pid_stats__field_indices_by_name[] = {
  1,   /* field[1] = count */
  2,   /* field[2] = pid_details */
  0,   /* field[0] = timestamp_ms */
};
static const ProtobufCIntRange gwstats__pid_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gwstats__pid_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.PidStats",
  "PidStats",
  "Gwstats__PidStats",
  "gwstats",
  sizeof(Gwstats__PidStats),
  3,
  gwstats__pid_stats__field_descriptors,
  gwstats__pid_stats__field_indices_by_name,
  1,  gwstats__pid_stats__number_ranges,
  (ProtobufCMessageInit) gwstats__pid_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gwstats__gateway_stats__field_descriptors[9] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gwstats__GatewayStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gwstats__GatewayStats, n_system),
    offsetof(Gwstats__GatewayStats, system),
    &gwstats__system_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wan",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gwstats__GatewayStats, n_wan),
    offsetof(Gwstats__GatewayStats, wan),
    &gwstats__wan_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lan",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gwstats__GatewayStats, n_lan),
    offsetof(Gwstats__GatewayStats, lan),
    &gwstats__lan_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_monitoring",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gwstats__GatewayStats, n_ipv6_monitoring),
    offsetof(Gwstats__GatewayStats, ipv6_monitoring),
    &gwstats__ipv6_monitoring_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gwstats__GatewayStats, n_tcp),
    offsetof(Gwstats__GatewayStats, tcp),
    &gwstats__tcp_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gwstats__GatewayStats, n_client),
    offsetof(Gwstats__GatewayStats, client),
    &gwstats__client_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Gwstats__GatewayStats, n_pid),
    offsetof(Gwstats__GatewayStats, pid),
    &gwstats__pid_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "restartCount",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gwstats__GatewayStats, restartcount),
    &gwstats__restart_count_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gwstats__gateway_stats__field_indices_by_name[] = {
  6,   /* field[6] = client */
  4,   /* field[4] = ipv6_monitoring */
  3,   /* field[3] = lan */
  7,   /* field[7] = pid */
  8,   /* field[8] = restartCount */
  1,   /* field[1] = system */
  5,   /* field[5] = tcp */
  0,   /* field[0] = timestamp_ms */
  2,   /* field[2] = wan */
};
static const ProtobufCIntRange gwstats__gateway_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor gwstats__gateway_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gwstats.GatewayStats",
  "GatewayStats",
  "Gwstats__GatewayStats",
  "gwstats",
  sizeof(Gwstats__GatewayStats),
  9,
  gwstats__gateway_stats__field_descriptors,
  gwstats__gateway_stats__field_indices_by_name,
  1,  gwstats__gateway_stats__number_ranges,
  (ProtobufCMessageInit) gwstats__gateway_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
