/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: docsis_stats.proto */

#ifndef PROTOBUF_C_docsis_5fstats_2eproto__INCLUDED
#define PROTOBUF_C_docsis_5fstats_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct DsChannelStats DsChannelStats;
typedef struct UsChannelStats UsChannelStats;
typedef struct Report Report;


/* --- enums --- */


/* --- messages --- */

/*
 * ===== Downstream Channel Stats =====
 */
struct  DsChannelStats
{
  ProtobufCMessage base;
  uint64_t timestamp_ms;
  uint32_t ds_channel_count;
  uint64_t channel_id;
  char *frequency;
  char *power_level;
  char *snr_level;
  char *modulation;
  uint64_t octets;
  uint64_t correcteds;
  uint64_t uncorrectables;
  char *lock_status;
};
#define DS_CHANNEL_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ds_channel_stats__descriptor) \
, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, (char *)protobuf_c_empty_string }


/*
 * ===== Upstream Channel Stats =====
 */
struct  UsChannelStats
{
  ProtobufCMessage base;
  uint64_t timestamp_ms;
  uint32_t us_channel_count;
  uint64_t channel_id;
  char *frequency;
  char *power_level;
  char *channel_type;
  char *symbol_rate;
  char *modulation;
  char *lock_status;
};
#define US_CHANNEL_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&us_channel_stats__descriptor) \
, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * //////////////////////////////////////////////////////////////////////////////
 * Overall report that contain all individual stats reports
 * //////////////////////////////////////////////////////////////////////////////
 */
struct  Report
{
  ProtobufCMessage base;
  size_t n_dschanneldata;
  DsChannelStats **dschanneldata;
  size_t n_uschanneldata;
  UsChannelStats **uschanneldata;
};
#define REPORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&report__descriptor) \
, 0,NULL, 0,NULL }


/* DsChannelStats methods */
void   ds_channel_stats__init
                     (DsChannelStats         *message);
size_t ds_channel_stats__get_packed_size
                     (const DsChannelStats   *message);
size_t ds_channel_stats__pack
                     (const DsChannelStats   *message,
                      uint8_t             *out);
size_t ds_channel_stats__pack_to_buffer
                     (const DsChannelStats   *message,
                      ProtobufCBuffer     *buffer);
DsChannelStats *
       ds_channel_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ds_channel_stats__free_unpacked
                     (DsChannelStats *message,
                      ProtobufCAllocator *allocator);
/* UsChannelStats methods */
void   us_channel_stats__init
                     (UsChannelStats         *message);
size_t us_channel_stats__get_packed_size
                     (const UsChannelStats   *message);
size_t us_channel_stats__pack
                     (const UsChannelStats   *message,
                      uint8_t             *out);
size_t us_channel_stats__pack_to_buffer
                     (const UsChannelStats   *message,
                      ProtobufCBuffer     *buffer);
UsChannelStats *
       us_channel_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   us_channel_stats__free_unpacked
                     (UsChannelStats *message,
                      ProtobufCAllocator *allocator);
/* Report methods */
void   report__init
                     (Report         *message);
size_t report__get_packed_size
                     (const Report   *message);
size_t report__pack
                     (const Report   *message,
                      uint8_t             *out);
size_t report__pack_to_buffer
                     (const Report   *message,
                      ProtobufCBuffer     *buffer);
Report *
       report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   report__free_unpacked
                     (Report *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DsChannelStats_Closure)
                 (const DsChannelStats *message,
                  void *closure_data);
typedef void (*UsChannelStats_Closure)
                 (const UsChannelStats *message,
                  void *closure_data);
typedef void (*Report_Closure)
                 (const Report *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ds_channel_stats__descriptor;
extern const ProtobufCMessageDescriptor us_channel_stats__descriptor;
extern const ProtobufCMessageDescriptor report__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_docsis_5fstats_2eproto__INCLUDED */
