/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gateway_stats.proto */

#ifndef PROTOBUF_C_gateway_5fstats_2eproto__INCLUDED
#define PROTOBUF_C_gateway_5fstats_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Gwstats__PidStats Gwstats__PidStats;
typedef struct Gwstats__SystemStats Gwstats__SystemStats;
typedef struct Gwstats__WanStats Gwstats__WanStats;
typedef struct Gwstats__ClientDetails Gwstats__ClientDetails;
typedef struct Gwstats__LanStats Gwstats__LanStats;
typedef struct Gwstats__IPv6MonitoringStats Gwstats__IPv6MonitoringStats;
typedef struct Gwstats__TcpStats Gwstats__TcpStats;
typedef struct Gwstats__RestartCountStats Gwstats__RestartCountStats;
typedef struct Gwstats__GatewayStats Gwstats__GatewayStats;


/* --- enums --- */


/* --- messages --- */

/*
 * ===== PID Stats =====
 */
struct  Gwstats__PidStats
{
  ProtobufCMessage base;
  uint32_t pid;
  char *pname;
  uint32_t rss;
  uint32_t pss;
  uint32_t mem_util;
  uint32_t cpu_util;
};
#define GWSTATS__PID_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gwstats__pid_stats__descriptor) \
, 0, (char *)protobuf_c_empty_string, 0, 0, 0, 0 }


/*
 * ===== System Stats =====
 */
struct  Gwstats__SystemStats
{
  ProtobufCMessage base;
  uint64_t timestamp_ms;
  char *model;
  char *firmware;
  char *cmac;
  char *uptime;
  double cpu_usage;
  double free_memory;
  double slab_memory;
  double avail_memory;
  double cached_mem;
  double slab_unreclaim;
  double loadavg_1min;
  double loadavg_5min;
  double loadavg_15min;
  uint32_t rootfs_used_kb;
  uint32_t rootfs_total_kb;
  uint32_t tmpfs_used_kb;
  uint32_t tmpfs_total_kb;
  int32_t pid_stats_count;
  size_t n_pid_stats;
  Gwstats__PidStats **pid_stats;
};
#define GWSTATS__SYSTEM_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gwstats__system_stats__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL }


/*
 * ===== WAN Stats =====
 */
struct  Gwstats__WanStats
{
  ProtobufCMessage base;
  uint64_t timestamp_ms;
  char *interface_status;
  char *ipv4_address;
  char *ipv6_address;
  char *gateway_status;
  double packet_loss;
  double latency;
  double jitter;
  double dns_time;
  char *rx_bytes;
  char *tx_bytes;
  char *rx_dropped;
  char *tx_dropped;
  char *ipv4_lease;
  char *ipv6_lease;
};
#define GWSTATS__WAN_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gwstats__wan_stats__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * ===== LAN Client Details =====
 */
struct  Gwstats__ClientDetails
{
  ProtobufCMessage base;
  char *mac_address;
  char *ip_addr;
  char *host_name;
  char *status;
  char *tx_bytes;
  char *rx_bytes;
  int32_t tcp_est_counts;
};
#define GWSTATS__CLIENT_DETAILS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gwstats__client_details__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/*
 * ===== LAN Stats =====
 */
struct  Gwstats__LanStats
{
  ProtobufCMessage base;
  uint64_t timestamp_ms;
  char *ipv4_address;
  char *ipv6_address;
  char *rx_bytes;
  char *tx_bytes;
  char *rx_dropped;
  char *tx_dropped;
  char *channel_util_2_4ghz;
  char *channel_util_5ghz;
  char *channel_util_6ghz;
  size_t n_clients;
  Gwstats__ClientDetails **clients;
  int32_t client_count;
};
#define GWSTATS__LAN_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gwstats__lan_stats__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0 }


/*
 * ===== IPv6 Monitoring Stats =====
 */
struct  Gwstats__IPv6MonitoringStats
{
  ProtobufCMessage base;
  uint64_t timestamp_ms;
  char *global_ipv6_address;
  char *link_local_ipv6_address;
  char *ipv6_reachability;
  double ipv4_latency;
  double ipv6_latency;
  double ipv4_packet_loss;
  double ipv6_packet_loss;
};
#define GWSTATS__IPV6_MONITORING_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gwstats__ipv6_monitoring_stats__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0 }


/*
 * ===== TCP Stats =====
 */
struct  Gwstats__TcpStats
{
  ProtobufCMessage base;
  uint64_t timestamp_ms;
  char *tcplostretransmit;
  char *tcpretransfail;
  char *tcpsackfailures;
  char *tcptimeouts;
  char *tcpabortontimeout;
  char *listenoverflows;
  char *tcporigdatasent;
};
#define GWSTATS__TCP_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gwstats__tcp_stats__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * ===== Restart Count Stats =====
 */
struct  Gwstats__RestartCountStats
{
  ProtobufCMessage base;
  int32_t fw_restart_count;
  size_t n_fw_restart_time;
  char **fw_restart_time;
  int32_t wan_restart_count;
  size_t n_wan_restart_time;
  char **wan_restart_time;
};
#define GWSTATS__RESTART_COUNT_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gwstats__restart_count_stats__descriptor) \
, 0, 0,NULL, 0, 0,NULL }


/*
 * //////////////////////////////////////////////////////////////////////////////
 * Overall report that contain all individual stats reports
 * //////////////////////////////////////////////////////////////////////////////
 */
struct  Gwstats__GatewayStats
{
  ProtobufCMessage base;
  uint64_t timestamp_ms;
  size_t n_system_stats;
  Gwstats__SystemStats **system_stats;
  size_t n_wan_stats;
  Gwstats__WanStats **wan_stats;
  size_t n_lan_stats;
  Gwstats__LanStats **lan_stats;
  size_t n_ipv6_stats;
  Gwstats__IPv6MonitoringStats **ipv6_stats;
  size_t n_tcp_stats;
  Gwstats__TcpStats **tcp_stats;
  Gwstats__RestartCountStats *restart_count_stats;
};
#define GWSTATS__GATEWAY_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gwstats__gateway_stats__descriptor) \
, 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, NULL }


/* Gwstats__PidStats methods */
void   gwstats__pid_stats__init
                     (Gwstats__PidStats         *message);
size_t gwstats__pid_stats__get_packed_size
                     (const Gwstats__PidStats   *message);
size_t gwstats__pid_stats__pack
                     (const Gwstats__PidStats   *message,
                      uint8_t             *out);
size_t gwstats__pid_stats__pack_to_buffer
                     (const Gwstats__PidStats   *message,
                      ProtobufCBuffer     *buffer);
Gwstats__PidStats *
       gwstats__pid_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gwstats__pid_stats__free_unpacked
                     (Gwstats__PidStats *message,
                      ProtobufCAllocator *allocator);
/* Gwstats__SystemStats methods */
void   gwstats__system_stats__init
                     (Gwstats__SystemStats         *message);
size_t gwstats__system_stats__get_packed_size
                     (const Gwstats__SystemStats   *message);
size_t gwstats__system_stats__pack
                     (const Gwstats__SystemStats   *message,
                      uint8_t             *out);
size_t gwstats__system_stats__pack_to_buffer
                     (const Gwstats__SystemStats   *message,
                      ProtobufCBuffer     *buffer);
Gwstats__SystemStats *
       gwstats__system_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gwstats__system_stats__free_unpacked
                     (Gwstats__SystemStats *message,
                      ProtobufCAllocator *allocator);
/* Gwstats__WanStats methods */
void   gwstats__wan_stats__init
                     (Gwstats__WanStats         *message);
size_t gwstats__wan_stats__get_packed_size
                     (const Gwstats__WanStats   *message);
size_t gwstats__wan_stats__pack
                     (const Gwstats__WanStats   *message,
                      uint8_t             *out);
size_t gwstats__wan_stats__pack_to_buffer
                     (const Gwstats__WanStats   *message,
                      ProtobufCBuffer     *buffer);
Gwstats__WanStats *
       gwstats__wan_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gwstats__wan_stats__free_unpacked
                     (Gwstats__WanStats *message,
                      ProtobufCAllocator *allocator);
/* Gwstats__ClientDetails methods */
void   gwstats__client_details__init
                     (Gwstats__ClientDetails         *message);
size_t gwstats__client_details__get_packed_size
                     (const Gwstats__ClientDetails   *message);
size_t gwstats__client_details__pack
                     (const Gwstats__ClientDetails   *message,
                      uint8_t             *out);
size_t gwstats__client_details__pack_to_buffer
                     (const Gwstats__ClientDetails   *message,
                      ProtobufCBuffer     *buffer);
Gwstats__ClientDetails *
       gwstats__client_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gwstats__client_details__free_unpacked
                     (Gwstats__ClientDetails *message,
                      ProtobufCAllocator *allocator);
/* Gwstats__LanStats methods */
void   gwstats__lan_stats__init
                     (Gwstats__LanStats         *message);
size_t gwstats__lan_stats__get_packed_size
                     (const Gwstats__LanStats   *message);
size_t gwstats__lan_stats__pack
                     (const Gwstats__LanStats   *message,
                      uint8_t             *out);
size_t gwstats__lan_stats__pack_to_buffer
                     (const Gwstats__LanStats   *message,
                      ProtobufCBuffer     *buffer);
Gwstats__LanStats *
       gwstats__lan_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gwstats__lan_stats__free_unpacked
                     (Gwstats__LanStats *message,
                      ProtobufCAllocator *allocator);
/* Gwstats__IPv6MonitoringStats methods */
void   gwstats__ipv6_monitoring_stats__init
                     (Gwstats__IPv6MonitoringStats         *message);
size_t gwstats__ipv6_monitoring_stats__get_packed_size
                     (const Gwstats__IPv6MonitoringStats   *message);
size_t gwstats__ipv6_monitoring_stats__pack
                     (const Gwstats__IPv6MonitoringStats   *message,
                      uint8_t             *out);
size_t gwstats__ipv6_monitoring_stats__pack_to_buffer
                     (const Gwstats__IPv6MonitoringStats   *message,
                      ProtobufCBuffer     *buffer);
Gwstats__IPv6MonitoringStats *
       gwstats__ipv6_monitoring_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gwstats__ipv6_monitoring_stats__free_unpacked
                     (Gwstats__IPv6MonitoringStats *message,
                      ProtobufCAllocator *allocator);
/* Gwstats__TcpStats methods */
void   gwstats__tcp_stats__init
                     (Gwstats__TcpStats         *message);
size_t gwstats__tcp_stats__get_packed_size
                     (const Gwstats__TcpStats   *message);
size_t gwstats__tcp_stats__pack
                     (const Gwstats__TcpStats   *message,
                      uint8_t             *out);
size_t gwstats__tcp_stats__pack_to_buffer
                     (const Gwstats__TcpStats   *message,
                      ProtobufCBuffer     *buffer);
Gwstats__TcpStats *
       gwstats__tcp_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gwstats__tcp_stats__free_unpacked
                     (Gwstats__TcpStats *message,
                      ProtobufCAllocator *allocator);
/* Gwstats__RestartCountStats methods */
void   gwstats__restart_count_stats__init
                     (Gwstats__RestartCountStats         *message);
size_t gwstats__restart_count_stats__get_packed_size
                     (const Gwstats__RestartCountStats   *message);
size_t gwstats__restart_count_stats__pack
                     (const Gwstats__RestartCountStats   *message,
                      uint8_t             *out);
size_t gwstats__restart_count_stats__pack_to_buffer
                     (const Gwstats__RestartCountStats   *message,
                      ProtobufCBuffer     *buffer);
Gwstats__RestartCountStats *
       gwstats__restart_count_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gwstats__restart_count_stats__free_unpacked
                     (Gwstats__RestartCountStats *message,
                      ProtobufCAllocator *allocator);
/* Gwstats__GatewayStats methods */
void   gwstats__gateway_stats__init
                     (Gwstats__GatewayStats         *message);
size_t gwstats__gateway_stats__get_packed_size
                     (const Gwstats__GatewayStats   *message);
size_t gwstats__gateway_stats__pack
                     (const Gwstats__GatewayStats   *message,
                      uint8_t             *out);
size_t gwstats__gateway_stats__pack_to_buffer
                     (const Gwstats__GatewayStats   *message,
                      ProtobufCBuffer     *buffer);
Gwstats__GatewayStats *
       gwstats__gateway_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gwstats__gateway_stats__free_unpacked
                     (Gwstats__GatewayStats *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Gwstats__PidStats_Closure)
                 (const Gwstats__PidStats *message,
                  void *closure_data);
typedef void (*Gwstats__SystemStats_Closure)
                 (const Gwstats__SystemStats *message,
                  void *closure_data);
typedef void (*Gwstats__WanStats_Closure)
                 (const Gwstats__WanStats *message,
                  void *closure_data);
typedef void (*Gwstats__ClientDetails_Closure)
                 (const Gwstats__ClientDetails *message,
                  void *closure_data);
typedef void (*Gwstats__LanStats_Closure)
                 (const Gwstats__LanStats *message,
                  void *closure_data);
typedef void (*Gwstats__IPv6MonitoringStats_Closure)
                 (const Gwstats__IPv6MonitoringStats *message,
                  void *closure_data);
typedef void (*Gwstats__TcpStats_Closure)
                 (const Gwstats__TcpStats *message,
                  void *closure_data);
typedef void (*Gwstats__RestartCountStats_Closure)
                 (const Gwstats__RestartCountStats *message,
                  void *closure_data);
typedef void (*Gwstats__GatewayStats_Closure)
                 (const Gwstats__GatewayStats *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor gwstats__pid_stats__descriptor;
extern const ProtobufCMessageDescriptor gwstats__system_stats__descriptor;
extern const ProtobufCMessageDescriptor gwstats__wan_stats__descriptor;
extern const ProtobufCMessageDescriptor gwstats__client_details__descriptor;
extern const ProtobufCMessageDescriptor gwstats__lan_stats__descriptor;
extern const ProtobufCMessageDescriptor gwstats__ipv6_monitoring_stats__descriptor;
extern const ProtobufCMessageDescriptor gwstats__tcp_stats__descriptor;
extern const ProtobufCMessageDescriptor gwstats__restart_count_stats__descriptor;
extern const ProtobufCMessageDescriptor gwstats__gateway_stats__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_gateway_5fstats_2eproto__INCLUDED */
