/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: docsis_stats.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "docsis_stats.pb-c.h"
void   ds_channel_stats__init
                     (DsChannelStats         *message)
{
  static const DsChannelStats init_value = DS_CHANNEL_STATS__INIT;
  *message = init_value;
}
size_t ds_channel_stats__get_packed_size
                     (const DsChannelStats *message)
{
  assert(message->base.descriptor == &ds_channel_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ds_channel_stats__pack
                     (const DsChannelStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ds_channel_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ds_channel_stats__pack_to_buffer
                     (const DsChannelStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ds_channel_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DsChannelStats *
       ds_channel_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DsChannelStats *)
     protobuf_c_message_unpack (&ds_channel_stats__descriptor,
                                allocator, len, data);
}
void   ds_channel_stats__free_unpacked
                     (DsChannelStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ds_channel_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   us_channel_stats__init
                     (UsChannelStats         *message)
{
  static const UsChannelStats init_value = US_CHANNEL_STATS__INIT;
  *message = init_value;
}
size_t us_channel_stats__get_packed_size
                     (const UsChannelStats *message)
{
  assert(message->base.descriptor == &us_channel_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t us_channel_stats__pack
                     (const UsChannelStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &us_channel_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t us_channel_stats__pack_to_buffer
                     (const UsChannelStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &us_channel_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UsChannelStats *
       us_channel_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UsChannelStats *)
     protobuf_c_message_unpack (&us_channel_stats__descriptor,
                                allocator, len, data);
}
void   us_channel_stats__free_unpacked
                     (UsChannelStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &us_channel_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   report__init
                     (Report         *message)
{
  static const Report init_value = REPORT__INIT;
  *message = init_value;
}
size_t report__get_packed_size
                     (const Report *message)
{
  assert(message->base.descriptor == &report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t report__pack
                     (const Report *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t report__pack_to_buffer
                     (const Report *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Report *
       report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Report *)
     protobuf_c_message_unpack (&report__descriptor,
                                allocator, len, data);
}
void   report__free_unpacked
                     (Report *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ds_channel_stats__field_descriptors[11] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ds_channel_count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, ds_channel_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, channel_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frequency",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, frequency),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power_level",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, power_level),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "snr_level",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, snr_level),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modulation",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, modulation),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "octets",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, octets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "correcteds",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, correcteds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uncorrectables",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, uncorrectables),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lock_status",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DsChannelStats, lock_status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ds_channel_stats__field_indices_by_name[] = {
  2,   /* field[2] = channel_id */
  8,   /* field[8] = correcteds */
  1,   /* field[1] = ds_channel_count */
  3,   /* field[3] = frequency */
  10,   /* field[10] = lock_status */
  6,   /* field[6] = modulation */
  7,   /* field[7] = octets */
  4,   /* field[4] = power_level */
  5,   /* field[5] = snr_level */
  0,   /* field[0] = timestamp_ms */
  9,   /* field[9] = uncorrectables */
};
static const ProtobufCIntRange ds_channel_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor ds_channel_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DsChannelStats",
  "DsChannelStats",
  "DsChannelStats",
  "",
  sizeof(DsChannelStats),
  11,
  ds_channel_stats__field_descriptors,
  ds_channel_stats__field_indices_by_name,
  1,  ds_channel_stats__number_ranges,
  (ProtobufCMessageInit) ds_channel_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor us_channel_stats__field_descriptors[9] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UsChannelStats, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "us_channel_count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UsChannelStats, us_channel_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UsChannelStats, channel_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frequency",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UsChannelStats, frequency),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power_level",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UsChannelStats, power_level),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel_type",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UsChannelStats, channel_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol_rate",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UsChannelStats, symbol_rate),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modulation",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UsChannelStats, modulation),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lock_status",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UsChannelStats, lock_status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned us_channel_stats__field_indices_by_name[] = {
  2,   /* field[2] = channel_id */
  5,   /* field[5] = channel_type */
  3,   /* field[3] = frequency */
  8,   /* field[8] = lock_status */
  7,   /* field[7] = modulation */
  4,   /* field[4] = power_level */
  6,   /* field[6] = symbol_rate */
  0,   /* field[0] = timestamp_ms */
  1,   /* field[1] = us_channel_count */
};
static const ProtobufCIntRange us_channel_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor us_channel_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UsChannelStats",
  "UsChannelStats",
  "UsChannelStats",
  "",
  sizeof(UsChannelStats),
  9,
  us_channel_stats__field_descriptors,
  us_channel_stats__field_indices_by_name,
  1,  us_channel_stats__number_ranges,
  (ProtobufCMessageInit) us_channel_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor report__field_descriptors[2] =
{
  {
    "dsChannelData",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Report, n_dschanneldata),
    offsetof(Report, dschanneldata),
    &ds_channel_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usChannelData",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Report, n_uschanneldata),
    offsetof(Report, uschanneldata),
    &us_channel_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned report__field_indices_by_name[] = {
  0,   /* field[0] = dsChannelData */
  1,   /* field[1] = usChannelData */
};
static const ProtobufCIntRange report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Report",
  "Report",
  "Report",
  "",
  sizeof(Report),
  2,
  report__field_descriptors,
  report__field_indices_by_name,
  1,  report__number_ranges,
  (ProtobufCMessageInit) report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
